# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 17:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitterHandle', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(max_length=60, null=True)),
                ('bio', models.TextField(null=True)),
                ('profilePic', models.ImageField(default='profilepics/placeholder.png', null=True, upload_to='profilepics')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachingPlanTitle', models.CharField(max_length=20)),
                ('coachingPlanType', models.TextField(blank=True, null=True)),
                ('coachingPlanDate', models.DateField(default=datetime.datetime.now, null=True)),
                ('coachingPlanDescription', models.TextField(blank=True, null=True)),
                ('coachingPlanNotes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosketch', models.TextField()),
                ('profilePic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drillTitle', models.CharField(max_length=20)),
                ('drillImage', models.TextField()),
                ('drillDescription', models.TextField()),
                ('drillType', models.CharField(choices=[('Attack', 'Attack Drill'), ('Defensive', 'Defensive Drill'), ('Passing', 'Passing Drill'), ('Dribbling', 'Dribbling Drill'), ('Shooting', 'Shooting Drill'), ('Crossing', 'Crossing Drill'), ('Goalie', 'Goalie Drill'), ('Other', 'Other')], max_length=20)),
                ('drillRate', models.IntegerField(null=True)),
                ('drillSetup', models.TextField()),
                ('drillInstruction', models.TextField()),
                ('drillDate', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineupStyle', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField(unique=True)),
                ('playerJerseyLabel', models.CharField(max_length=3)),
                ('playerGoalCount', models.IntegerField()),
                ('playerYellowCard', models.IntegerField()),
                ('PlayerRedCard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='playersCoach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.User'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='LineupOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.User'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='LineupPlayers',
            field=models.ManyToManyField(to='GafferApp.Player'),
        ),
        migrations.AddField(
            model_name='drill',
            name='drillOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='GafferApp.Drill'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='profileOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GafferApp.User'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='coachingPlanDrill',
            field=models.ManyToManyField(to='GafferApp.Drill'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='coachingPlanOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
